<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5c80ea6c2b7d7',
	'title' => 'Tab Clone Settings: General',
	'fields' => array(
		array(
			'key' => 'field_5c896d0ca5b65',
			'label' => 'Labels',
			'name' => 'labels',
			'type' => 'select',
			'instructions' => 'Placeholders will be automatically added if labels are hidden.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top' => 'Top',
				'left' => 'Left',
				'hide_labels' => 'Hide Labels',
			),
			'default_value' => array(
				0 => 'top',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c80ea6c2fb10',
			'label' => 'Wrap Form',
			'name' => 'wrap_form',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Adds a border around the form and removes border from error messages.',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c81398d14242',
			'label' => 'Transparent Inputs',
			'name' => 'transparent_inputs',
			'type' => 'true_false',
			'instructions' => 'Remove input background and top, right, left borders.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c80ea6c2fb1c',
			'label' => 'Submit Button Text',
			'name' => 'submit_button_text',
			'type' => 'text',
			'instructions' => 'Leave blank to use default.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Submit Form',
			'prepend' => '',
			'append' => '',
			'maxlength' => 30,
		),
		array(
			'key' => 'field_5c80ea6c2fb28',
			'label' => 'User Confirmation Email',
			'name' => 'user_confirmation_email',
			'type' => 'select',
			'instructions' => 'How confirmations email are handled.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'ask' => 'Always Ask User',
				'send' => 'Always Send',
				'never' => 'Never Send',
			),
			'default_value' => array(
				0 => 'ask',
			),
			'allow_null' => 1,
			'multiple' => 0,
			'ui' => 0,
			'ajax' => 0,
			'return_format' => 'value',
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c80ea6c2fb33',
			'label' => 'Show Page in Email',
			'name' => 'show_page_in_email',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c80ea6c2fb28',
						'operator' => '==',
						'value' => 'ask',
					),
				),
				array(
					array(
						'field' => 'field_5c80ea6c2fb28',
						'operator' => '==',
						'value' => 'send',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Show page name and link in email. (Useful if form appears on multiple pages.)',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c80ea6c2fb3f',
			'label' => 'Show Edit Link',
			'name' => 'show_edit_link',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Shows an <b>Edit Form</b> link to users with form editing capabilities.',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c80ea6c2fb4a',
			'label' => 'Tab Index',
			'name' => 'tab_index',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 100,
			'prepend' => '',
			'append' => '',
			'min' => 0,
			'max' => '',
			'step' => 100,
		),
		array(
			'key' => 'field_5c8ab19817df1',
			'label' => 'Colour Theme',
			'name' => 'colour_theme',
			'type' => 'select',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'dark' => 'Dark (Standard)',
				'light' => 'Light',
			),
			'default_value' => array(
				0 => 'dark',
			),
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_5c8ab10c17dee',
			'label' => 'CSS',
			'name' => 'css',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5c8ab12e17def',
					'label' => 'Wrapper ID',
					'name' => 'wrapper_id',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5c8ab13e17df0',
					'label' => 'Wrapper Class',
					'name' => 'wrapper_class',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5d0b8b8a46e9e',
			'label' => 'Displaying Results',
			'name' => 'displaying_results',
			'type' => 'group',
			'instructions' => 'These features require ajax to be activated.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5d0f672ef6739',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5d0b8bb346e9f',
					'label' => 'Results Modal',
					'name' => 'results_modal',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '20',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 1,
					'ui' => 1,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
				array(
					'key' => 'field_5d0b8bef46ea0',
					'label' => 'DOM Element to Inject',
					'name' => 'dom_element_to_inject',
					'type' => 'text',
					'instructions' => 'CSS id or unique class',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0b8bb346e9f',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5d0b8c9de62d9',
					'label' => 'DOM Element to Remove',
					'name' => 'dom_element_to_remove',
					'type' => 'text',
					'instructions' => 'CSS id or unique class',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_5d0b8bb346e9f',
								'operator' => '!=',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '40',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5c80ea9626f3d',
			'label' => 'Next Button in Sections',
			'name' => 'next_button_in_sections',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5c8b8293904b0',
			'label' => 'Show Section Stage Guide',
			'name' => 'show_section_stage_guide',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5c80ea9626f3d',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5d0f672ef6739',
			'label' => 'Ajax',
			'name' => 'ajax',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'wp_swift_form',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => false,
	'description' => '',
));

endif;