<?php
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

function form_shortcode_get_meta( $value ) {
    global $post;

    $field = get_post_meta( $post->ID, $value, true );
    if ( ! empty( $field ) ) {
        return is_array( $field ) ? stripslashes_deep( $field ) : stripslashes( wp_kses_decode_entities( $field ) );
    } else {
        return false;
    }
}

function form_shortcode_add_meta_box() {
    add_meta_box(
        'form_shortcode-form-shortcode',
        __( 'Form Shortcode', 'form_shortcode' ),
        'form_shortcode_html',
        'wp_swift_form',
        'side',
        'high'
    );
}
add_action( 'add_meta_boxes', 'form_shortcode_add_meta_box' );

function form_shortcode_html( $post) {
	// $id = get_the_id();
?>
<p>Copy the shortcode below in to the page editor/</p>
<input id="shortcode-input" type="text" value='[form id="<?php echo $post->ID ?>"]' readonly>
<a href="#" id="shortcode-input-copy">Copy</a>
<div id="shortcode-input-copy" class="hidden"><small>Shortcode Copied</small></div>
<?php 
// onclick="this.focus();this.select()" onfocus="this.focus();this.select();"
}