<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_57b6fd868aeca',
	'title' => 'Form Builder: Inputs',
	'fields' => array(
		array(
			'key' => 'field_5bfbdbf17c286',
			'label' => 'Form Inputs',
			'name' => 'form_inputs',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5bfbdc059cf1f' => array(
					'key' => '5bfbdc059cf1f',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfbe1fa8489d',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bfbfb3a38d65',
							'label' => 'Input Validation',
							'name' => 'input_validation',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbfa5f2b3c5',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5c000ed2fca73',
							'label' => 'CSS',
							'name' => 'css',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c0006eaba5e2',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfbe529c4e24' => array(
					'key' => '5bfbe529c4e24',
					'name' => 'number',
					'label' => 'Number',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfbe529c4e25',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bfbf6b7cf6b1',
							'label' => 'Number Attributes',
							'name' => 'number_attributes',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbf616f078b',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfbe541c4e26' => array(
					'key' => '5bfbe541c4e26',
					'name' => 'email',
					'label' => 'Email',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfbe541c4e27',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfc1076266b8' => array(
					'key' => '5bfc1076266b8',
					'name' => 'url',
					'label' => 'URL',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfc1076266b9',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfc04cea33af' => array(
					'key' => '5bfc04cea33af',
					'name' => 'textarea',
					'label' => 'Textarea',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfc04cea33b0',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bfc0609a33b1',
							'label' => 'Textarea Attributes',
							'name' => 'textarea_attributes',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfc056f8d9d6',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfc10ee90f64' => array(
					'key' => '5bfc10ee90f64',
					'name' => 'date',
					'label' => 'Date',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfc10ee90f65',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bfc11cc90f66',
							'label' => 'Date Ranges',
							'name' => 'date_ranges',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfc115dc78ac',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfc148c130f2' => array(
					'key' => '5bfc148c130f2',
					'name' => 'date_range',
					'label' => 'Date Range',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfc148c130f3',
							'label' => 'ID Group',
							'name' => 'id_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbdda24b2a3',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bfc14cd130f5',
							'label' => 'Reporting Group',
							'name' => 'reporting_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe09d3bf4f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfc19def84e5' => array(
					'key' => '5bfc19def84e5',
					'name' => 'select',
					'label' => 'Select',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfc1b467a6e5',
							'label' => 'Options Clone',
							'name' => 'options_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfc1a3251d65',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5bffdcaac79e0',
							'label' => 'Select Options',
							'name' => 'select_options',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bffdbed2c31f',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5c0012f1f36d6',
							'label' => 'CSS',
							'name' => 'css',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c0006eaba5e2',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfc274ab2982' => array(
					'key' => '5bfc274ab2982',
					'name' => 'checkbox',
					'label' => 'Checkbox',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfc274ab2983',
							'label' => 'Options Clone',
							'name' => 'options_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfc1a3251d65',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5c00098ae33da',
							'label' => 'CSS',
							'name' => 'css',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c00082667cf5',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5c6b1afb04e99',
							'label' => 'Options Layout',
							'name' => 'options_layout',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c6b0b129bb02',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'5bfd0506f4506' => array(
					'key' => '5bfd0506f4506',
					'name' => 'radio',
					'label' => 'Radio Button',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5bfd0506f4507',
							'label' => 'Options Clone',
							'name' => 'options_clone',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfc1a3251d65',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5c6b0bb4e43c1',
							'label' => 'Options Layout',
							'name' => 'options_layout',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5c6b0b129bb02',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5c0110f6844d6' => array(
					'key' => 'layout_5c0110f6844d6',
					'name' => 'file',
					'label' => 'File',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5c011109844d7',
							'label' => 'Default Group',
							'name' => 'default_group',
							'type' => 'clone',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'clone' => array(
								0 => 'group_5bfbe43dbc9a8',
							),
							'display' => 'seamless',
							'layout' => 'block',
							'prefix_label' => 0,
							'prefix_name' => 0,
						),
						array(
							'key' => 'field_5c011142844d8',
							'label' => 'Save Location',
							'name' => 'save_location',
							'type' => 'text',
							'instructions' => 'Ensure that Directory Listing is disabled on this folder for sensitive files.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => 'uploads',
							'placeholder' => 'uploads',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Input',
			'min' => '',
			'max' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

endif;