<?php
$path = plugin_dir_path( __FILE__ );
require_once $path . '_form-builder-clone-css-and-disabled.php';
require_once $path . '_form-builder-clone-css.php';
require_once $path . '_form-builder-clone-date-ranges.php';
require_once $path . '_form-builder-clone-group-default-settings.php';
require_once $path . '_form-builder-clone-id-group.php';
require_once $path . '_form-builder-clone-input-validation.php';
require_once $path . '_form-builder-clone-number-attributes.php';
require_once $path . '_form-builder-clone-options.php';
require_once $path . '_form-builder-clone-options-layout.php';
require_once $path . '_form-builder-clone-reporting-group.php';
require_once $path . '_form-builder-clone-select-options.php';
require_once $path . '_form-builder-clone-settings-group.php';
require_once $path . '_form-builder-clone-textarea-attributes.php';
require_once $path . '_form-builder-inputs.php';
require_once $path . '_form-builder-type-clone-contact-form-response.php';
require_once $path . 'tabs/_tab-clone-settings-inputs.php';
require_once $path . 'tabs/_tab-clone-settings-general.php';
require_once $path . 'tabs/_tab-clone-settings-spam-prevention.php';
require_once $path . 'tabs/_tab-clone-settings-marketing.php';
require_once $path . 'tabs/_tab-clone-settings-form-types.php';
require_once $path . 'main/_form-builder-input-sections.php';
require_once $path . '_form-builder-clone-group-default-settings.php';
require_once $path . 'options-pages/marketing.php';