<?php
function wp_swift_form_builder_get_array_ire_counties() {
	return array ( "array" => array(
        'Antrim'  => 'Antrim',
        'Armagh'  => 'Armagh',
        'Carlow' => 'Carlow',
        'Cavan' => 'Cavan',
        'Clare' => 'Clare',
        'Cork' => 'Cork',
        'Derry' => 'Derry/Londonderry',
        'Donegal' => 'Donegal',
        'Down'  => 'Down',
        'Dublin' => 'Dublin',
        'Fermanagh' => 'Fermanagh',
        'Galway' => 'Galway',
        'Kerry' => 'Kerry',
        'Kildare' => 'Kildare',
        'Kilkenny' => 'Kilkenny',
        'Laois' => 'Laois',
        'Leitrim' => 'Leitrim',
        'Limerick' => 'Limerick',
        'Longford' => 'Longford',
        'Louth' => 'Louth',
        'Mayo' => 'Mayo',
        'Meath' => 'Meath',
        'Monaghan' => 'Monaghan',
        'Offaly' => 'Offaly',
        'Roscommon' => 'Roscommon',
        'Sligo' => 'Sligo',
        'Tipperary' => 'Tipperary',
        'Tyrone'  => 'Tyrone',
        'Waterford' => 'Waterford',
        'Westmeath' => 'Westmeath',
        'Wexford' => 'Wexford',
        'Wicklow' => 'Wicklow'
	));
}