<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
	'key' => 'group_57b6fd868aeca',
	'title' => 'Form Builder: Inputs',
	'fields' => array (
		array (
			'key' => 'field_57b6fd8692eb1',
			'label' => 'Form Inputs',
			'name' => 'form_inputs',
			'type' => 'repeater',
			'value' => NULL,
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_59cfa87e380ec',
			'min' => 0,
			'max' => 0,
			'layout' => 'block',
			'button_label' => 'Add Input',
			'sub_fields' => array (
				array (
					'key' => 'field_59cfa87e380ec',
					'label' => 'ID Group',
					'name' => 'id',
					'type' => 'group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_59cfa8b2380ed',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'value' => NULL,
							'instructions' => 'Input identifier',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Eg. First Name',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59cfa8d9380ee',
							'label' => 'Label',
							'name' => 'label',
							'type' => 'text',
							'value' => NULL,
							'instructions' => 'If different from name',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array (
					'key' => 'field_59cfa9ddb6e14',
					'label' => 'Reporting Group',
					'name' => 'reporting',
					'type' => 'group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_59cfa9fab6e15',
							'label' => 'Help Message',
							'name' => 'help',
							'type' => 'text',
							'value' => NULL,
							'instructions' => 'Displayed on error',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => 'Eg. Email is not required but must be valid',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array (
							'key' => 'field_59cfaaa2c2584',
							'label' => 'Instructions',
							'name' => 'instructions',
							'type' => 'text',
							'value' => NULL,
							'instructions' => 'A visible message',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
					),
				),
				array (
					'key' => 'field_59cfb1a898f6b',
					'label' => 'Settings Group',
					'name' => 'settings',
					'type' => 'group',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'table',
					'sub_fields' => array (
						array (
							'key' => 'field_59cfb32e98f6d',
							'label' => 'Required',
							'name' => 'required',
							'type' => 'true_false',
							'value' => NULL,
							'instructions' => 'Force input from user',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '50',
								'class' => '',
								'id' => '',
							),
							'message' => 'Required is set by default',
							'default_value' => 1,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array (
							'key' => 'field_59cfb37e98f6e',
							'label' => 'Grouping',
							'name' => 'grouping',
							'type' => 'select',
							'value' => NULL,
							'instructions' => 'Manage multiple inputs in a row',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'none' => 'None',
								'start' => 'Start Group',
								'end' => 'End Group',
							),
							'default_value' => array (
								0 => 'none',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
				),
				array (
					'key' => 'field_59cfb79c09c69',
					'label' => 'Type',
					'name' => 'type',
					'type' => 'select',
					'value' => NULL,
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'text' => 'Text (Default)',
						'email' => 'Email',
						'number' => 'Number',
						'url' => 'URL',
						'textarea' => 'Text Area (Multi-line Text)',
						'select' => 'Select',
						'multi_select' => 'Multiple Select',
						'checkbox' => 'Checkboxes',
						'radio' => 'Radio Buttons',
						'file' => 'File Upload',
						'date' => 'Date',
						'date_time' => 'Date & Time Combo',
						'date_range' => 'Date Range',
					),
					'default_value' => array (
						0 => 'text',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
				array (
					'key' => 'field_57b6fd86d2e5f',
					'label' => 'Placeholder',
					'name' => 'placeholder',
					'type' => 'text',
					'value' => NULL,
					'instructions' => 'Specifies a short hint for input',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'text',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'email',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'number',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'url',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'textarea',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57b6fd86d2e84',
					'label' => 'Select Options',
					'name' => 'select_options',
					'type' => 'repeater',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'select',
							),
							array (
								'field' => 'field_57b6fd86d2e9f',
								'operator' => '==',
								'value' => 'user',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'multi_select',
							),
							array (
								'field' => 'field_57b6fd86d2e9f',
								'operator' => '==',
								'value' => 'user',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'checkbox',
							),
							array (
								'field' => 'field_57b6fd86d2e9f',
								'operator' => '==',
								'value' => 'user',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'radio',
							),
							array (
								'field' => 'field_57b6fd86d2e9f',
								'operator' => '==',
								'value' => 'user',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => 'field_57b6fd86e9a8c',
					'min' => 0,
					'max' => 0,
					'layout' => 'table',
					'button_label' => 'Add Option',
					'sub_fields' => array (
						array (
							'key' => 'field_57b6fd86e9a8c',
							'label' => 'Option',
							'name' => 'option',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
						array (
							'key' => 'field_57b6fd86e9aa8',
							'label' => 'Option Value',
							'name' => 'option_value',
							'type' => 'text',
							'value' => NULL,
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
							'readonly' => 0,
							'disabled' => 0,
						),
					),
				),
				array (
					'key' => 'field_57b6fd86d2e9f',
					'label' => 'Select Type',
					'name' => 'select_type',
					'type' => 'radio',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'select',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'multi_select',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'user' => 'Manually Input',
						'select' => 'Use Predefined Options',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => 'user',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_57b6fd86d2eb9',
					'label' => 'Predefined Options',
					'name' => 'predefined_options',
					'type' => 'select',
					'value' => NULL,
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'select',
							),
							array (
								'field' => 'field_57b6fd86d2e9f',
								'operator' => '==',
								'value' => 'select',
							),
						),
						array (
							array (
								'field' => 'field_59cfb79c09c69',
								'operator' => '==',
								'value' => 'multi_select',
							),
							array (
								'field' => 'field_57b6fd86d2e9f',
								'operator' => '==',
								'value' => 'select',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'countries' => 'Countries',
					),
					'default_value' => array (
						0 => 'countries',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'post',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 0,
	'description' => '',
));

endif;